### ISSUE TITLE
Installation & Usage: use rsync --modify-window instead of --size-only

### ISSUE THREAD

**Issue by pbtsrc** [Adonai/MARC-FS#4]
It seems one should use rsync --modify-window=1 instead of --size-only.

man rsync:
--modify-window
    When comparing two timestamps, rsync treats the timestamps as being equal if they differ by no more than the modify-window value. This is normally 0 (for an exact match), but you may find it useful to set this to a larger value in some situations. In particular, when transferring to or from an MS Windows FAT filesystem (which represents times with a 2-second resolution), --modify-window=1 is useful (allowing times to differ by up to 1 second).

**Comment by Adonai** [comment]
Sounds good to me. Will do.

**Comment by Adonai** [comment]
Fixed in 94d27cd3
